### ISSUE TITLE
Cant select 100% quality in msi

### ISSUE THREAD

**Issue by isaksc2** [juniorsgithub/tf2-how-to-record-depth#2]
Hey, thanks for the great guide. I have lagarith installed and followed the steps to the letter but the quality slider is greyed out and locked at 85%. Maybe its ok but I wanted to hear if you happened to know if there's a fix. Thanks!

**Comment by jooonior** [comment]
assuming you're talking about _Video capture > Video capture properties > n% quality slider_

This setting only applies to lossy codecs. Lagarith is always lossless, so it has no effect (that's why it's greyed out).

If you want to change it for placebo reasons, you have to switch to a lossy codec (like MJPG), slide it around, then switch back to Lagarith.

**Comment by jooonior** [comment]
Also I have improved the workflow quite a bit since I wrote this guide (less input heavy, less game crashes). I'll try to write a V2 today. If you can wait, it will save you some effort.

**Comment by isaksc2** [comment]
oh damn awesome, thanks a lot!
